import OpenAI from "openai";
import { ConsultationResult } from "./specialist.js";

const ai = new OpenAI({
  baseURL: "https://api.featherless.ai/v1",
  apiKey: process.env.FEATHERLESS_API_KEY!,
});

export interface SummaryReport {
  patientSymptoms: string;
  overallUrgency: "routine" | "urgent" | "immediate";
  primaryDiagnosis: string;
  specialistFindings: { specialist: string; summary: string }[];
  consolidatedRecommendations: string[];
  followUpPlan: string;
  disclaimer: string;
}

export async function generateSummaryReport(
  symptoms: string,
  consultations: ConsultationResult[]
): Promise<SummaryReport> {
  console.log("\n📝 Summary Agent: Compiling report...");

  const consultationText = consultations
    .map(
      (c) =>
        `${c.specialist.toUpperCase()}: ${c.findings} (Urgency: ${c.urgency})\nRecommendations: ${c.recommendations.join(", ")}`
    )
    .join("\n\n");

  const response = await ai.chat.completions.create({
    model: "deepseek-ai/DeepSeek-V3-0324",
    messages: [
      {
        role: "system",
        content: `You are a Medical Summary AI agent. You receive findings from multiple specialist agents and compile them into a clear, actionable patient report.

Respond in JSON only:
{
  "overallUrgency": "routine|urgent|immediate",
  "primaryDiagnosis": "most likely condition based on all findings",
  "specialistFindings": [{"specialist": "name", "summary": "one sentence summary"}],
  "consolidatedRecommendations": ["top 5 actionable recommendations"],
  "followUpPlan": "suggested next steps for the patient"
}`,
      },
      {
        role: "user",
        content: `Patient symptoms: ${symptoms}\n\nSpecialist consultations:\n${consultationText}`,
      },
    ],
    response_format: { type: "json_object" },
  });

  const report = JSON.parse(response.choices[0].message.content!);

  return {
    patientSymptoms: symptoms,
    overallUrgency: report.overallUrgency,
    primaryDiagnosis: report.primaryDiagnosis,
    specialistFindings: report.specialistFindings,
    consolidatedRecommendations: report.consolidatedRecommendations,
    followUpPlan: report.followUpPlan,
    disclaimer:
      "⚠️ This report is generated by AI agents for demonstration purposes only. Always consult a qualified medical professional for real health concerns.",
  };
}
